#!/usr/bin/env node

var ghpages = require('gh-pages');
var path = require('path');

ghpages.publish(path.join(__dirname, '../dist'), {
  message: 'Deploy frontend'
}, function(err) {
  if (err) console.error(err);
  else console.log('Application pushed to gh-pages branch');
});
